### ISSUE TITLE
Problem with understanding motivation for this project.

### ISSUE THREAD

**Issue by piotr-dobrogost** [insidewhy/kwin-window-switch#1]
I have some trouble understanding motivation which is currently stated as:

> The default KDE window switcher involves a "tab box" mode which blocks all further key bindings until the modifier key is removed. This script switches windows immediately without blocking key bindings.

What _blocking_ do you have in mind? Do you want to switch to some window and activate some key binding in this new window without releasing modifier key (I assume <kbd>Alt</kbd>) used to switch to this new window?

**Comment by insidewhy** [comment]
It's easier to explain with an example:

I use Meta+H and Meta+L to switch desktops. I use Meta+J and Meta+K to switch windows on a desktop. Like the classic vim movement layouts. I set up window switcher to not use animations. When I hit Meta+J or Meta+K it selects the next window on a desktop but even though I've set it to not use an animation it also enters "tab box mode". The problem with this mode is it blocks all future shortcuts until Meta is released. Another problem is that entering and leaving tab box mode introduces a bit of latency.

I switching windows a lot and very quickly during web development, from my coding desktop and then through various browsers on another desktop, those delays really add up and having to keep releasing the meta key only to push it again is also frustrating and slows me down. It makes my whole experience of using KWin feel so much less fluid than other window managers. The great thing about KDE though is it has the hooks and stuff for power users so we can overcome these things and as much as I love awesome I also really like Kwin!

🌵

**Comment by piotr-dobrogost** [comment]
You described how you switch desktops and windows but you still did not provide specific example so I'm not sure I follow. You mentioned that switching windows blocks subsequent shortcuts but I'm not sure why you mentioned switching windows and not desktops. I would understand if you wanted to switch desktop first and then without releasing <kbd>Meta</kbd> key switch to specific window inside this desktop. However switching to some window and then switching to another desktop does not make sense to me. I must be missing something...

**Comment by insidewhy** [comment]
Doesn't make sense? I do it all the time. Konsole+tmux on desktop one, code change triggers auto reload of two browsers on desktop 2. I can quickly check out the style changes and return to the first desktop without releasing meta. Although I use it in many more mundane ways than that also, it just springs to mind. The delay is also annoying, it may only be a few milliseconds but it ruins the feel for me. Much prefer immediate window switches.

**Comment by insidewhy** [comment]
A simpler example is switching to a window in order to close it. I have to release meta then push it again before hitting c which is my binding for close.
